In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


##Tensor

###Creating
pytorch tensors = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar 标量
scalar = torch.tensor(7)
# 输出标量
scalar
# 输出数据的维度
print(scalar.ndim)
#
scalar.item()

0


7

In [3]:
# Vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.item)
# Check shape of vector
print(vector.shape)

tensor([7, 7])
1
<built-in method item of Tensor object at 0x7f3278989a80>
torch.Size([2])


In [4]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX1 = torch.tensor([[7, 8], [9, 10], [1, 1]])
print(MATRIX)
# Check number of dimensions
print(MATRIX.ndim)
# 深度为2 宽度为2
print(MATRIX.shape)
# Check number of dimensions
print(MATRIX1.ndim)
# 深度为3 宽度为2
print(MATRIX1.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
2
torch.Size([3, 2])


In [5]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
              [3, 6, 9],
                [2, 4, 5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [6]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.dtype)
print(random_tensor.shape)

# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros.dtype)

# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

tensor([[0.2090, 0.1465, 0.7226, 0.5135],
        [0.7858, 0.1304, 0.1841, 0.5454],
        [0.0104, 0.3481, 0.0948, 0.9990]])
torch.float32
torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [7]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=1, end=10, step=1)
zero_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [9]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

### Tensor datatypes
tensor datatypes is one of the 3 big errors you will run into pytorch&deep learning:

1:tensors are not right datatype

2:tensors not right shape

3:tensors not on the right device

In [10]:
float_16_tensor1 = float_32_tensor.type(torch.float16)
float_16_tensor1

tensor([3., 6., 9.], dtype=torch.float16)

In [11]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=)
int_32_tensor
int_32_tensor.dtype

SyntaxError: ignored

In [ ]:
float_16_tensor1 * int_32_tensor

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"tensor is stored on:{some_tensor.device}")

### Manipulating Tensors

Tensor operation include：

 * Addition
 *subtration
 *mul
 *division
 *matrix mul

In [ ]:
# creat a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

In [ ]:
tensor = tensor *10
print(tensor)

In [ ]:
torch.mul(tensor, 10)

### 矩阵计算
torch.mm = torch.matmul

In [ ]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

In [ ]:
# Element-wise matrix multiplication
tensor * tensor

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

In [ ]:
%%time
torch.matmul(tensor, tensor)

### 最常见的错误

In [ ]:
# Shapes need to be in the right way
import torch
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

torch.matmul(tensor_A, tensor_B.T)

### 找特殊值，最大最小平均
x.max 或 torch.max(x)

In [12]:
# Create a tensor
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [13]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [14]:
tensor = torch.arange(10., 100., 10.)
print(tensor)

tensor_float8 = tensor.type(torch.float16)
print(tensor_float8)

# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])
tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)


tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## reshaping stacking squeezing unsqueezing
* reshaping
* stacking
* squeeze removes all 1 dimensionf from a tensor
* unsqueeze

In [27]:
import torch
x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [28]:
x_reshape = x.reshape(3, 3)
print(x_reshape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [29]:
# change the view,创建一个相同的tensor
z = x.view(3, 3)
z, z.shape, x

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [30]:
# 改变这个tensor会改变原始的tensor
z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [38]:
# stack of tensor 堆
# Stack tensors on top of each other
# hstack 和 vstack的区别
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [44]:
x_reshape = torch.reshape(x_reshape, [1, 9])
print(x_reshape)


tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])


torch.Size([9])

In [45]:
x_reshape.shape

torch.Size([1, 9])

In [51]:
x_squeeze = x_reshape.squeeze()

In [52]:
x_reshape.squeeze().shape

torch.Size([9])

In [64]:
# unsqueeze, 添加一个维度
print(f"previous target:{x_squeeze}")
print(f"previous shape:{x_squeeze.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeeze.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target:tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
previous shape:torch.Size([9])

New tensor: tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
New shape: torch.Size([1, 9])


In [69]:
#permute
x_original = torch.rand(size=(224, 224, 3))

x_permute = x_original.permute(2, 0, 1)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permute.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Index

In [73]:
import torch
x= torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [74]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
x[0][0]

tensor([1, 2, 3])

In [79]:
x[0][2][2]

tensor(9)

In [83]:
x[:, :, 0]

tensor([[1, 4, 7]])

## pytorch and Numpy
* data in numpy


In [84]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [86]:
tensor.dtype

torch.float64

In [89]:
# tensor to numpy 不用同一存储
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## reproducbility

In [91]:
import torch
torch.rand(3, 3)
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8977, 0.1225, 0.1247, 0.6530],
        [0.5041, 0.7771, 0.4053, 0.0392],
        [0.4866, 0.1144, 0.8754, 0.8739]])
tensor([[0.0870, 0.2559, 0.6414, 0.7699],
        [0.0185, 0.6866, 0.5263, 0.7165],
        [0.3588, 0.6897, 0.0414, 0.9061]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [96]:
import torch

RANDOM_SEED  =100
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## GPU

In [1]:
!nvidia-smi

Wed Dec 27 12:14:10 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
# check gpu forpytorch
import torch
torch.cuda.is_available()

True

In [4]:
device = "cuda"if torch.cuda.is_available else "cpu"
device

'cuda'

In [7]:
torch.cuda.device_count()

1

## putting tensors on gpu

In [8]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [10]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [11]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')